from dash import dcc, html
from ..config import df_columns, df_columns_full, df_groups
import dash_bootstrap_components as dbc


def generate_description_card():
    """

    :return: A Div containing dashboard title & descriptions.
    """
    return html.Div(
        id="description-card",
        children=[
            html.H5("Example dashboard"),
            html.Div(
                id="intro",
                children="You can use this as a basic template for your JBI100 visualization project.",
            ),
        ],
    )


def generate_control_card():
    """

    :return: A Div containing controls for graphs.
    """
    return html.Div(
        id="control-card",
        children=[
            dbc.Button("Dataset information", id="open", n_clicks=0),
            dbc.Modal(
                [
                    dbc.ModalHeader(dbc.ModalTitle("TIC Data description")),
                    dbc.ModalBody(children=[
                                    html.Div(
                                        "Each observation corresponds to a postal code. Variables beginning with M refer to "
                                        "demographic statistics of the postal code, while variables beginning with P and A (as "
                                        "well as CARAVAN, the target variable) refer to product ownership and insurance "
                                        "statistics in the postal code."),
                                    html.Div("\n"),
                                    html.Div("The data file contains the following fields:"),
                                    html.Div("\n"),
                                    html.Div("ORIGIN: train or test, as described above"),
                                    html.Div("MOSTYPE: Customer Subtype; see L0"),
                                    html.Div("MAANTHUI: Number of houses 1 - 10"),
                                    html.Div("MGEMOMV: Avg size household 1 - 6"),
                                    html.Div("MGEMLEEF: Avg age; see L1"),
                                    html.Div("MOSHOOFD: Customer main type; see L2"),
                                    html.Div("** Percentages in each group, per postal code (see L3)**:"),
                                    html.Div("\n"),
                                    html.Div("MGODRK: Roman catholic"),
                                    html.Div("MGODPR: Protestant …"),
                                    html.Div("MGODOV: Other religion"),
                                    html.Div("MGODGE: No religion"),
                                    html.Div("\n"),
                                    html.Div("MRELGE: Married"),
                                    html.Div("MRELSA: Living together"),
                                    html.Div("MRELOV: Other relation"),
                                    html.Div("MFALLEEN: Singles"),
                                    html.Div("\n"),
                                    html.Div("MFGEKIND: Household without children"),
                                    html.Div("MFWEKIND: Household with children"),
                                    html.Div("\n"),
                                    html.Div("MOPLHOOG: High level education"),
                                    html.Div("MOPLMIDD: Medium level education"),
                                    html.Div("MOPLLAAG: Lower level education"),
                                    html.Div("\n"),
                                    html.Div("MBERHOOG: High status"),
                                    html.Div("MBERZELF: Entrepreneur"),
                                    html.Div("MBERBOER: Farmer"),
                                    html.Div("MBERMIDD: Middle management"),
                                    html.Div("MBERARBG: Skilled labourers"),
                                    html.Div("MBERARBO: Unskilled labourers"),
                                    html.Div("\n"),
                                    html.Div("MSKA: Social class A"),
                                    html.Div("MSKB1: Social class B1"),
                                    html.Div("MSKB2: Social class B2"),
                                    html.Div("MSKC: Social class C"),
                                    html.Div("MSKD: Social class D"),
                                    html.Div("\n"),
                                    html.Div("MHHUUR: Rented house"),
                                    html.Div("MHKOOP: Home owners"),
                                    html.Div("\n"),
                                    html.Div("MAUT1: 1 car"),
                                    html.Div("MAUT2: 2 cars"),
                                    html.Div("MAUT0: No car"),
                                    html.Div("\n"),
                                    html.Div("MZFONDS: National Health Service"),
                                    html.Div("MZPART: Private health insurance"),
                                    html.Div("\n"),
                                    html.Div("MINKM30: Income < 30.000"),
                                    html.Div("MINK3045: Income 30-45.000"),
                                    html.Div("MINK4575: Income 45-75.000"),
                                    html.Div("MINK7512: Income 75-122.000"),
                                    html.Div("MINK123M: Income >123.000"),
                                    html.Div("MINKGEM: Average income"),
                                    html.Div("\n"),
                                    html.Div("MKOOPKLA: Purchasing power class"),
                                    html.Div("** Total number of variable in postal code (see L4)**:"),
                                    html.Div("\n"),
                                    html.Div("PWAPART: Contribution private third party insurance"),
                                    html.Div("PWABEDR: Contribution third party insurance (firms) …"),
                                    html.Div("PWALAND: Contribution third party insurane (agriculture)"),
                                    html.Div("PPERSAUT: Contribution car policies"),
                                    html.Div("PBESAUT: Contribution delivery van policies"),
                                    html.Div("PMOTSCO: Contribution motorcycle/scooter policies"),
                                    html.Div("PVRAAUT: Contribution lorry policies"),
                                    html.Div("PAANHANG: Contribution trailer policies"),
                                    html.Div("PTRACTOR: Contribution tractor policies"),
                                    html.Div("PWERKT: Contribution agricultural machines policies"),
                                    html.Div("PBROM: Contribution moped policies"),
                                    html.Div("PLEVEN: Contribution life insurances"),
                                    html.Div("PPERSONG: Contribution private accident insurance policies"),
                                    html.Div("PGEZONG: Contribution family accidents insurance policies"),
                                    html.Div("PWAOREG: Contribution disability insurance policies"),
                                    html.Div("PBRAND: Contribution fire policies"),
                                    html.Div("PZEILPL: Contribution surfboard policies"),
                                    html.Div("PPLEZIER: Contribution boat policies"),
                                    html.Div("PFIETS: Contribution bicycle policies"),
                                    html.Div("PINBOED: Contribution property insurance policies"),
                                    html.Div("PBYSTAND: Contribution social security insurance policies"),
                                    html.Div("AWAPART: Number of private third party insurance 1 - 12"),
                                    html.Div("AWABEDR: Number of third party insurance (firms) …"),
                                    html.Div("AWALAND: Number of third party insurance (agriculture)"),
                                    html.Div("APERSAUT: Number of car policies"),
                                    html.Div("ABESAUT: Number of delivery van policies"),
                                    html.Div("AMOTSCO: Number of motorcycle/scooter policies"),
                                    html.Div("AVRAAUT: Number of lorry policies"),
                                    html.Div("AAANHANG: Number of trailer policies"),
                                    html.Div("ATRACTOR: Number of tractor policies"),
                                    html.Div("AWERKT: Number of agricultural machines policies"),
                                    html.Div("ABROM: Number of moped policies"),
                                    html.Div("ALEVEN: Number of life insurances"),
                                    html.Div("APERSONG: Number of private accident insurance policies"),
                                    html.Div("AGEZONG: Number of family accidents insurance policies"),
                                    html.Div("AWAOREG: Number of disability insurance policies"),
                                    html.Div("ABRAND: Number of fire policies"),
                                    html.Div("AZEILPL: Number of surfboard policies"),
                                    html.Div("APLEZIER: Number of boat policies"),
                                    html.Div("AFIETS: Number of bicycle policies"),
                                    html.Div("AINBOED: Number of property insurance policies"),
                                    html.Div("ABYSTAND: Number of social security insurance policies"),
                                    html.Div("CARAVAN: Number of mobile home policies 0 - 1"),
                                    html.Div("\n"),
                                    html.Div("\n"),
                                    html.Div("Keys (L1 - L4)"),
                                    html.Div("\n"),
                                    html.Div("L0: Customer subtype"),
                                    html.Div("\n"),
                                    html.Div("1: High Income, expensive child"),
                                    html.Div("2: Very Important Provincials"),
                                    html.Div("3: High status seniors"),
                                    html.Div("4: Affluent senior apartments"),
                                    html.Div("5: Mixed seniors"),
                                    html.Div("6: Career and childcare"),
                                    html.Div("7: Dinki's (double income no kids)"),
                                    html.Div("8: Middle class families"),
                                    html.Div("9: Modern, complete families"),
                                    html.Div("10: Stable family"),
                                    html.Div("11: Family starters"),
                                    html.Div("12: Affluent young families"),
                                    html.Div("13: Young all american family"),
                                    html.Div("14: Junior cosmopolitan"),
                                    html.Div("15: Senior cosmopolitans"),
                                    html.Div("16: Students in apartments"),
                                    html.Div("17: Fresh masters in the city"),
                                    html.Div("18: Single youth"),
                                    html.Div("19: Suburban youth"),
                                    html.Div("20: Etnically diverse"),
                                    html.Div("21: Young urban have-nots"),
                                    html.Div("22: Mixed apartment dwellers"),
                                    html.Div("23: Young and rising"),
                                    html.Div("24: Young, low educated"),
                                    html.Div("25: Young seniors in the city"),
                                    html.Div("26: Own home elderly"),
                                    html.Div("27: Seniors in apartments"),
                                    html.Div("28: Residential elderly"),
                                    html.Div("29: Porchless seniors: no front yard"),
                                    html.Div("30: Religious elderly singles"),
                                    html.Div("31: Low income catholics"),
                                    html.Div("32: Mixed seniors"),
                                    html.Div("33: Lower class large families"),
                                    html.Div("34: Large family, employed child"),
                                    html.Div("35: Village families"),
                                    html.Div("36: Couples with teens 'Married with children'"),
                                    html.Div("37: Mixed small town dwellers"),
                                    html.Div("38: Traditional families"),
                                    html.Div("39: Large religous families"),
                                    html.Div("40: Large family farms"),
                                    html.Div("41: Mixed rurals"),
                                    html.Div("\n"),
                                    html.Div("L1: average age keys:"),
                                    html.Div("\n"),
                                    html.Div("1: 20-30 years"),
                                    html.Div("2: 30-40 years"),
                                    html.Div("3: 40-50 years"),
                                    html.Div("4: 50-60 years"),
                                    html.Div("5: 60-70 years"),
                                    html.Div("6: 70-80 years"),
                                    html.Div("\n"),
                                    html.Div("L2: customer main type keys:"),
                                    html.Div("\n"),
                                    html.Div("1: Successful hedonists"),
                                    html.Div("2: Driven Growers"),
                                    html.Div("3: Average Family"),
                                    html.Div("4: Career Loners"),
                                    html.Div("5: Living well"),
                                    html.Div("6: Cruising Seniors"),
                                    html.Div("7: Retired and Religeous"),
                                    html.Div("8: Family with grown ups"),
                                    html.Div("9: Conservative families"),
                                    html.Div("10: Farmers"),
                                    html.Div("\n"),
                                    html.Div("L3: percentage keys:"),
                                    html.Div("\n"),
                                    html.Div("0: 0%"),
                                    html.Div("1: 1 - 10%"),
                                    html.Div("2: 11 - 23%"),
                                    html.Div("3: 24 - 36%"),
                                    html.Div("4: 37 - 49%"),
                                    html.Div("5: 50 - 62%"),
                                    html.Div("6: 63 - 75%"),
                                    html.Div("7: 76 - 88%"),
                                    html.Div("8: 89 - 99%"),
                                    html.Div("9: 100%"),
                                    html.Div("\n"),
                                    html.Div("L4: total number keys:"),
                                    html.Div("\n"),
                                    html.Div("0: 0"),
                                    html.Div("1: 1 - 49"),
                                    html.Div("2: 50 - 99"),
                                    html.Div("3: 100 - 199"),
                                    html.Div("4: 200 - 499"),
                                    html.Div("5: 500 - 999"),
                                    html.Div("6: 1000 - 4999"),
                                    html.Div("7: 5000 - 9999"),
                                    html.Div("8: 10,000 - 19,999"),
                                    html.Div("9: >= 20,000")
                                ],
                        style={"white-space": "pre-line"},
                    ),
                ],
                id="modal",
                size="xl",
                is_open=False,
            ),
            html.H4("Data exploration"),
            html.Label("PCP column selector"),
            dcc.Dropdown(
                id="select-columns-pcp",
                options=[{"label": i.capitalize(), "value": i} for i in df_columns_full if i != "ORIGIN"],
                value=df_columns,
                multi=True,
            ),
            html.Br(),
            html.Label("Attribute distribution"),
            dcc.Dropdown(
                id="select-single-attr",
                options=[{"label": i.capitalize(), "value": i} for i in df_columns_full if i != "ORIGIN"],
                value="MOSTYPE",
            ),
            html.Br(),
            html.Label("Attribute group distribution"),
            dcc.Dropdown(
                id="select-group-attr",
                options=[{"label": i.capitalize(), "value": i} for i in df_groups],
                value=df_groups[0],
            ),
            html.H4("Model exploration"),
            html.Label("Model choice"),
            dcc.Dropdown(
                id="select-model",
                options=[{"label": i, "value": i} for i in ["Naive Bayes classifier",
                                                            "Decision Tree classifier"]],
                value="Decision Tree classifier",
            ),
        ], style={"textAlign": "float-left"}
    )


def make_menu_layout():
    return [generate_description_card(), generate_control_card()]
